---
:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - [mailers, 10]
  - [default, 5]

:max_retries: 25

production:
  :concurrency: 10

development:
  :concurrency: 2

test:
  :concurrency: 1
